### ISSUE TITLE
`sbt new` does not work

### ISSUE THREAD

**Issue by Tilakkumar** [akka/akka-http-quickstart-scala.g8#15] opened 2017-08-14 09:14 UTC
Hi,

In windows 10, it shows below error.

> Exiting due to error in the template
> File: C:\Users\TILAK~1.NAR\AppData\Local\Temp\giter8-331126442355577\src\main\g8\src\main\scala\com\lightbend\akka\http\sample\UserRegistryActor.scala, 30:53: 'created' came as a complete surprise to me

**Comment by jrudolph** [comment] 2017-08-14 09:43
@Tilakkumar, interesting. Can you add a bit more information about what you did exactly to get this error?

(Btw. for anyone else who is wondering: "came as a complete surprise to me" is an actual error message from [ANTLR](https://github.com/antlr/antlr4/blob/274120c2b6ea059ad8e9538103163667d2575a2c/tool/src/org/antlr/v4/parse/ToolANTLRParser.java#L69))

**Comment by Tilakkumar** [comment] 2017-08-14 10:15
Hi Jrudolph,

Installed JDK8, sbt 0.13.13 and scala 2.12.3. From windows command prompt invoked command "sbt new https://github.com/akka/akka-http-scala-seed.g8"

Thanks

**Comment by jrudolph** [comment] 2017-08-14 10:44
Might not even be related to Windows, it can be reproduced by running `g8Test` in the template sbt project.

I guess Scala string interpolation and giter8's templating language might be conflicting there.

**Comment by jlprat** [comment] 2017-08-14 10:53
Why travis is not failing then?

**Comment by jrudolph** [comment] 2017-08-14 10:54
Here a similar issue was reported: https://github.com/foundweekends/giter8/issues/288#issuecomment-312626433

The workaround is to use `\$` instead of plain `$` in scala sources inside of g8 templates. Another variant would be using `$"$name"$`.

**Comment by jrudolph** [comment] 2017-08-14 11:36
@jlprat I guess for multiple reasons:

 * `g8Test` is not used in travis build
 * `g8Test` doesn't fail because there seems to be some fallback solution that is triggered when the template generation doesn't work using scalasti / StringTemplate:

```
Falling back to file copy for UserRegistryActor.scala: File: UserRegistryActor.scala, 30:53: 'created' came as a complete surprise to me
```

**Comment by jlprat** [comment] 2017-08-14 14:51
Thanks for the explanation :+1:

**Comment by leosimoesp** [comment] 2017-08-16 22:42
Hi,
When this patch will be available to use ?
I've done git clone to generate new project locally. Is it possible ?
Thanks,

**Comment by ktoso** [comment] 2017-08-17 01:42
The patch is merged now, though I'm not sure if that's all it takes to make it work again.
Keeping ticket open for now

**Comment by jlprat** [comment] 2017-08-17 07:29
I was able to do `sbt -Dsbt.version=0.13.15 new https://github.com/akka/akka-http-scala-seed.g8` successfully, and also the created project could be started

**Comment by leosimoesp** [comment] 2017-08-17 12:57
Thanks guys, I got it too.

**Comment by jlprat** [comment] 2017-08-17 13:01
Then I'll close it. Please ping back if you find out it's still not working!

**Closed by jlprat** 2017-08-17 13:01 UTC
